artifacts:
  - name: "@daiyam/artifact-lang-js"
    version: 0.6.1
  - name: "@daiyam/artifact-lang-ts"
    version: 0.5.3
  - name: "@daiyam/artifact-npm-ts"
    version: 0.3.1
  - name: "@daiyam/artifact-npm-daiyam"
    version: 0.2.1
  - name: "@daiyam/artifact-test-mocha-ts"
    version: 0.4.0
