artifacts:
  - name: "@daiyam/artifact-lang-js"
    version: 0.6.0
  - name: "@daiyam/artifact-lang-ts"
    version: 0.5.0
  - name: "@daiyam/artifact-npm-ts"
    version: 0.3.0
  - name: "@daiyam/artifact-npm-daiyam"
    version: 0.2.0
  - name: "@daiyam/artifact-test-mocha-ts"
    version: 0.4.0
